language: csharp
mono: none
sudo: required
dist: xenial
dotnet: 2.2
solution: influxdb-client-csharp.sln

services:
  - docker

env:
  - INFLUXDB_VERSION=1.7 INFLUXDB_V2_REPOSITORY=influxdb INFLUXDB_2_VERSION=2.0.0-beta
  - INFLUXDB_VERSION=1.7 INFLUXDB_V2_REPOSITORY=influx INFLUXDB_2_VERSION=nightly

install: true

jobs:
  include:
    - script:
        - ./Scripts/influxdb-restart.sh
        - dotnet tool install --tool-path="./Coverlet/" coverlet.console
        - dotnet restore
        - dotnet build
        - dotnet test Client.Legacy.Test
        - dotnet test Client.Test

after_success:
  - ./Coverlet/coverlet Client.Legacy.Test/bin/Debug/netcoreapp2.2/Client.Legacy.Test.dll --target "dotnet" --targetargs "test Client.Legacy.Test/Client.Legacy.Test.csproj --no-build" --format opencover --output "./Client.Legacy.Test/"
  - ./Coverlet/coverlet Client.Test/bin/Debug/netcoreapp2.2/Client.Test.dll --target "dotnet"  --targetargs "test Client.Test/Client.Test.csproj --no-build" --format opencover --output "./Client.Test/"
  - bash <(curl -s https://codecov.io/bash)
  
