apiRules:
- exclude:
    uidRegex: ^InfluxDB\.Client\.Api\.Client$
    type: Namespace
- exclude:
    uidRegex: ^InfluxDB\.Client\.Configurations$
    type: Namespace
- exclude:
    uidRegex: ^InfluxDB\.Client\.Core\.Internal$
    type: Namespace
- exclude:
    uidRegex: ^InfluxDB\.Client\.Core\.Flux\.Internal$
    type: Namespace